### ISSUE TITLE
Resolution changes are not detected when connecting/disconnecting screens

### ISSUE THREAD

**Issue by zenitraM** [koekeishiya/chunkwm#368]
Steps to reproduce:
- Have MBP with an external screen, with the resolution of the built-in screen set different when unplugged and plugged (when I have an external monitor plugged, I have a lower built-in screen density as I need less space for windows).
- Plug or unplug the screen.

The display disconnection is detected properly and all windows are moved properly to a single screen. However, the resolution chunkwm thinks this monitor have is set to the one before the disconnection, causing the windows to overflow or to stay on a small section of the screen.

I have only tried with density changes (Retina screen, with same physical resolution but different scaled resolutions), not real resolution changes so not sure if it would make a difference. However, when changing the density from the Display panel or Resolutionator the resolution change is picked up properly by chunkwm - it's only when unplugging/plugging when it doesn't get recognized.

**Comment by koekeishiya** [comment]
There has yet to be done any work that allows hotplugging monitors. See #16 
This is not a feature that is very useful for me personally, and the monitor handling in macOS is really damn poor and frustrating to interact with, so I don't expect to be doing any work here anytime soon.

**Comment by zenitraM** [comment]
I'll try to setup a dev environment and experiment with this if I find some time. Monitor hotplugging seems to work fine for me otherwise except for this little quirk.

Thanks for the great work on chunkwm!

**Comment by koekeishiya** [comment]
This is somewhat related to #313 and #45

**Comment by koekeishiya** [comment]
After quite a while of thinking, this issue is somewhat isolated from the other multi-monitor complexity, and I have implemented support for this on the master branch.

**Comment by zxaos** [comment]
I'm still seeing this on 0.3.9, but it might be related to unplugging monitors when the machine is slept.
