### ISSUE TITLE
Request: Ability to use chunkwm with multiple users

### ISSUE THREAD

**Issue by remi-gelinas** [koekeishiya/chunkwm#434]
I have multiple user accounts (personal, work, etc.) and I've noticed that chunkwm can only be run in one account at any given time, I guess because of the port already being listened to.

Is there any possibility that there could be a solution for using it on multiple accounts at the same time in the future?

**Comment by chris-kahn** [comment]
I'd really like to see this too.

**Comment by koekeishiya** [comment]
This is because the port is already bound by the previous chunkwm instance. I suppose we could get around this by using a fd handle that is local to the specific user.

We would however need a way to have this fd be shared between chunkwm and chunkc, so that chunkc can send commands. This would most likely require the introduction of an environment variable "CHUNKWM_SOCKET" or something that the user must specify.

If chunkwm / chunkc are launched through launchd, this var must probably be set in the launchd.plist configuration.

**Comment by koekeishiya** [comment]
Fixed on master. chunkwm now uses a unix file stored as `/tmp/chunkwm_$USER-socket` instead of listening on a given port. We use a pid-file `/tmp/chunkwm_$USER-pid` to make sure only one instance of chunkwm is running for that user.

**Comment by chris-kahn** [comment]
I've updated to latest master and it's still not working... I do see these socket and pid files created in /tmp for both of my users. However, when I try to run chunkwm from my second user I get:

```
$ chunkwm
chunkwm: could not access accessibility features! abort..
```

And similarly when I run `brew services start chunkwm` and checking in console:

```
-[TCCDAccessIdentity staticCode]: static code for: identifier /usr/local/opt/chunkwm/bin/chunkwm, type: 1: 0x7fea14543690 at /usr/local/opt/chunkwm/bin/chunkwm
-[PersistentAppsSupport applicationQuit:] | for app:chunkwm, _appTrackingState = 2
```

It seems like it just gets stuck in a restarting loop.

**Comment by chris-kahn** [comment]
But yes, I did get the accessibility features popup, I deleted and then re-checked chunkwm from the accessibility list.
